# Generated by Django 3.2.6 on 2021-08-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telefone',
            new_name='cellphone',
        ),
    ]
