# Generated by Django 3.2.5 on 2021-08-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.TextField(blank=True),
        ),
    ]
